server:
  contextPath: /vitalsport/profile
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/vitalsport
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        cache:
          use_second_level_cache: false
          use_structured_entities: true
        generate_statistics: false
vitalsport:
  secretKey: verySecretKey
